version: '3.9'
services:
  readme.notify.smtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: readme.notify.smtp
    hostname: readme.notify.smtp
    environment:
      FAKESMTP_AUTHENTICATION_USERNAME: ${MAIL_USERNAME}
      FAKESMTP_AUTHENTICATION_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - 8025:8025
      - 1083:8080

  readme.notify.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: readme.notify.rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 1088:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  readme.notify.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.notify.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - readme.notify.mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-notify --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.notify.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.notify.mongo.ui
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@readme.notify.mongo:27017/

volumes:
  readme.notify.mongo:

